// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/dhikr/domain/entities/dhikr_definition.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 7837403286889798015),
      name: 'DhikrDefinitionEntity',
      lastPropertyId: const obx_int.IdUid(15, 3978832424527002492),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4885415537204801871),
            name: 'objectBoxId',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7660501994880844891),
            name: 'id',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(1, 9014654759481701213)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5705287401113277239),
            name: 'maxCount',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1795798516300165588),
            name: 'currentCount',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 5161230015852708454),
            name: 'completedCount',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 3672214216375202306),
            name: 'arabicText',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 564905934991567312),
            name: 'enTitle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 763485389218864135),
            name: 'bdTitle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 8570821906904808806),
            name: 'bdPronunciation',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 6592113033380498935),
            name: 'bdTranslation',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 1650468034347497129),
            name: 'enPronunciation',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 9018689045466061123),
            name: 'enTranslation',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 3978832424527002492),
            name: 'reference',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 7837403286889798015),
      lastIndexId: const obx_int.IdUid(1, 9014654759481701213),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [1050622584608071366, 4536480623105018370],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    DhikrDefinitionEntity: obx_int.EntityDefinition<DhikrDefinitionEntity>(
        model: _entities[0],
        toOneRelations: (DhikrDefinitionEntity object) => [],
        toManyRelations: (DhikrDefinitionEntity object) => {},
        getId: (DhikrDefinitionEntity object) => object.objectBoxId,
        setId: (DhikrDefinitionEntity object, int id) {
          object.objectBoxId = id;
        },
        objectToFB: (DhikrDefinitionEntity object, fb.Builder fbb) {
          final idOffset = fbb.writeString(object.id);
          final arabicTextOffset = fbb.writeString(object.arabicText);
          final enTitleOffset = fbb.writeString(object.enTitle);
          final bdTitleOffset = fbb.writeString(object.bdTitle);
          final bdPronunciationOffset = fbb.writeString(object.bdPronunciation);
          final bdTranslationOffset = fbb.writeString(object.bdTranslation);
          final enPronunciationOffset = fbb.writeString(object.enPronunciation);
          final enTranslationOffset = fbb.writeString(object.enTranslation);
          final referenceOffset = fbb.writeString(object.reference);
          fbb.startTable(16);
          fbb.addInt64(0, object.objectBoxId ?? 0);
          fbb.addOffset(1, idOffset);
          fbb.addInt64(4, object.maxCount);
          fbb.addInt64(5, object.currentCount);
          fbb.addInt64(6, object.completedCount);
          fbb.addOffset(7, arabicTextOffset);
          fbb.addOffset(8, enTitleOffset);
          fbb.addOffset(9, bdTitleOffset);
          fbb.addOffset(10, bdPronunciationOffset);
          fbb.addOffset(11, bdTranslationOffset);
          fbb.addOffset(12, enPronunciationOffset);
          fbb.addOffset(13, enTranslationOffset);
          fbb.addOffset(14, referenceOffset);
          fbb.finish(fbb.endTable());
          return object.objectBoxId ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final objectBoxIdParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          final idParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final arabicTextParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 18, '');
          final enTitleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 20, '');
          final bdTitleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 22, '');
          final bdPronunciationParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 24, '');
          final bdTranslationParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 26, '');
          final enPronunciationParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 28, '');
          final enTranslationParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 30, '');
          final referenceParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 32, '');
          final maxCountParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final currentCountParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final completedCountParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16);
          final object = DhikrDefinitionEntity(
              objectBoxId: objectBoxIdParam,
              id: idParam,
              arabicText: arabicTextParam,
              enTitle: enTitleParam,
              bdTitle: bdTitleParam,
              bdPronunciation: bdPronunciationParam,
              bdTranslation: bdTranslationParam,
              enPronunciation: enPronunciationParam,
              enTranslation: enTranslationParam,
              reference: referenceParam,
              maxCount: maxCountParam,
              currentCount: currentCountParam,
              completedCount: completedCountParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DhikrDefinitionEntity] entity fields to define ObjectBox queries.
class DhikrDefinitionEntity_ {
  /// See [DhikrDefinitionEntity.objectBoxId].
  static final objectBoxId = obx.QueryIntegerProperty<DhikrDefinitionEntity>(
      _entities[0].properties[0]);

  /// See [DhikrDefinitionEntity.id].
  static final id = obx.QueryStringProperty<DhikrDefinitionEntity>(
      _entities[0].properties[1]);

  /// See [DhikrDefinitionEntity.maxCount].
  static final maxCount = obx.QueryIntegerProperty<DhikrDefinitionEntity>(
      _entities[0].properties[2]);

  /// See [DhikrDefinitionEntity.currentCount].
  static final currentCount = obx.QueryIntegerProperty<DhikrDefinitionEntity>(
      _entities[0].properties[3]);

  /// See [DhikrDefinitionEntity.completedCount].
  static final completedCount = obx.QueryIntegerProperty<DhikrDefinitionEntity>(
      _entities[0].properties[4]);

  /// See [DhikrDefinitionEntity.arabicText].
  static final arabicText = obx.QueryStringProperty<DhikrDefinitionEntity>(
      _entities[0].properties[5]);

  /// See [DhikrDefinitionEntity.enTitle].
  static final enTitle = obx.QueryStringProperty<DhikrDefinitionEntity>(
      _entities[0].properties[6]);

  /// See [DhikrDefinitionEntity.bdTitle].
  static final bdTitle = obx.QueryStringProperty<DhikrDefinitionEntity>(
      _entities[0].properties[7]);

  /// See [DhikrDefinitionEntity.bdPronunciation].
  static final bdPronunciation = obx.QueryStringProperty<DhikrDefinitionEntity>(
      _entities[0].properties[8]);

  /// See [DhikrDefinitionEntity.bdTranslation].
  static final bdTranslation = obx.QueryStringProperty<DhikrDefinitionEntity>(
      _entities[0].properties[9]);

  /// See [DhikrDefinitionEntity.enPronunciation].
  static final enPronunciation = obx.QueryStringProperty<DhikrDefinitionEntity>(
      _entities[0].properties[10]);

  /// See [DhikrDefinitionEntity.enTranslation].
  static final enTranslation = obx.QueryStringProperty<DhikrDefinitionEntity>(
      _entities[0].properties[11]);

  /// See [DhikrDefinitionEntity.reference].
  static final reference = obx.QueryStringProperty<DhikrDefinitionEntity>(
      _entities[0].properties[12]);
}
